### ISSUE TITLE
Update Controllers to Return 404 Status Code for Nonexistent IDs in GET Requests

### ISSUE THREAD

**Issue by RutiRozenberg** [npmStart0/server#3]
The task involves modifying all controllers to ensure that the GET function, which receives an ID and returns the corresponding object, returns a 404 status code when an ID that does not exist is provided instead of the current 400 status code. Currently, the issue lies in the incorrect status code being returned for non-existent IDs, and this needs to be rectified for better error handling and response consistency. The goal is to enhance the API behavior to align with standard practices and improve the overall user experience by providing accurate status codes based on the request outcome.

**Comment by 100michal100** [comment]
הי , אני אעשה את המשימה 
תודה

**Comment by RutiRozenberg** [comment]
Please write in English

**Comment by 100michal100** [comment]
Hi, I wanted to mannage this, and I noticed someone has already done it. 
Additionally, if you want to improve the writing, 
I heard from an instructor in the course that it's better to perform all these checks, including the status return checks,
 in the BL layer, so the code in the controller is as clean as possible, only invoking the function in the BL with try-catch . 
Let me know what sould i do about this...
Thank you

**Comment by RutiRozenberg** [comment]
The current requirement is to return a 404 status code when a non-existent ID is provided in the GET request. However, despite the presence of code intended to handle this scenario, the system is currently returning a 400 status code instead of the expected 404.

To verify this discrepancy, I recommend checking the Swagger documentation, where you can observe the actual status codes being returned.
