### ISSUE TITLE
Ensure API Returns 400 Status Code for Data Update and Creation Errors

### ISSUE THREAD

**Issue by sarihaiman** [npmStart0/server#6]
The bug was previously fixed

**Comment by RutiRozenberg** [comment]
Hi @sarihaiman 

To optimize our efforts and focus on current priorities, I would like to propose a new task for you to work on. The new task aligns with our current development objectives and will allow you to contribute to the project effectively.

Please consider the following task: #8  . This task is essential and will help us progress towards our project goals.

I value your contributions to the team and look forward to seeing your expertise in action on this new task. If you have any questions or need additional information, please don't hesitate to reach out.

Thank you for your understanding and flexibility in adapting to the evolving requirements of the project.
